### PR TITLE
fix(build): add ambient type definitions

### PR DESCRIPTION
**Pull request by mgechev**
1. Update to TypeScript (1.9 has fix for TS4020).
2. Update ts-node and typings.
3. Add ambient type definitions for CacheStorage, CacheOptions, Cache.
4. Add ambient type definitions for jshashes.
5. Remove useless require from `gulpfile.ts`.
6. Add `merge-stream` in order to merge both js and dts streams of
`gulp-typescript`.
7. Publish `typings` field in `package.json`.
8. Remove inline Promise interface definition and take the one from
`es6-shim` typings.

Note that the `Cache` interfaces does not completely align [to the standard](https://www.w3.org/TR/service-workers/#cache).

### CODE REVIEW

**Comment by jeffbcross** [comment]
Awesome, are you planning to update the build process to emit `dist/worker.d.ts` as part of this PR?

**Comment by mgechev** [comment]
Yes, sure. What do you think about the standard compatibility? Should we keep the definitions as they are, or to make align to the w3c?

**Comment by jeffbcross** [comment]
Personally, I see the typings as a stop gap until Cache typings are included in TypeScript. I don't think they need to be complete.

**Comment by mgechev** [comment]
@jeffbcross everything from https://github.com/angular/progressive/issues/15 should be here.

All merge conflicts are resolved and the PR is squashed.

**Comment by mgechev** [comment]
Need to rebase. I'll do that when I land.

**Comment by mgechev** [comment]
@jeffbcross, we have green build. I incorporated https://github.com/angular/mobile-toolkit/pull/16/commits/0ff0b1c0b456baf39f47c102f31b83f4e57cf00b here and added a few more enhancements on top.

I edited the commit message above with all the changes.

Let me know if you prefer the two commits squashed into a single one.

**Pull request merged**
